---
- name: Update Vault Secrets
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "engine_type"
      prompt: "Please enter the engine type (pki, ssh, or kv)"
      private: no
      default: "kv"

    - name: "engine_name"
      prompt: "Please enter the engine name"
      private: no

    - name: "secret_name"
      prompt: "Please enter the secret name"
      private: no
  
  pre_tasks:
    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_engines"

    - name: Validate engine exists
      when: engine_name not in existing_engines
      block:
        - name: Error message
          ansible.builtin.debug:
            msg: "Engine '{{ existing_engines }}' does not exist."

        - name: Stop execution
          meta: end_play

    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_secrets"

    - name: Validate secret exists
      when: secret_name in existing_secrets
      block:
        - name: Error message
          ansible.builtin.debug:
            msg: "Secret '{{ secret_name }}' already exists."

        - name: Stop execution
          meta: end_play

    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "create_secret_{{ engine_type }}"

