---
- hosts: localhost
  gather_facts: no
  vars:
    #engine_type: kv
    #engine_type: ssh
    engine_type: pki
    engine_name: pki-a
  
  pre_tasks:
    - name: Ensure environment variables are set
      block:
        - name: VAULT_TOKEN
          fail:
            msg: "VAULT_TOKEN environment variable is not set"
          when: lookup('env', 'VAULT_TOKEN') == ""

        - name: VAULT_ADDR
          fail:
            msg: "VAULT_ADDR environment variable is not set"
          when: lookup('env', 'VAULT_ADDR') == ""

        - name: Set Vars
          set_fact:
            vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
            vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"

  tasks:
    - name: Enable Engine
      when: engine_type in ["kv", "ssh", "pki"]
      block:
        - name: Create body
          when: engine_type == "kv"
          set_fact:
            body: 
              type: "kv"
              options: 
                version: "2"

        - name: Create body
          when: engine_type == "ssh"
          set_fact:
            body:
              type: "ssh"

        - name: Create body
          when: engine_type == "pki"
          set_fact:
            body:
              type: "pki"

        - name: Create Engine
          uri:
            url: "{{ lookup('env', 'VAULT_ADDR') }}/v1/sys/mounts/{{ engine_name }}"
            method: POST
            headers:
              X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
            body: "{{ body }}"
            status_code: [200, 201, 204]
            body_format: json
            return_content: true
            validate_certs: false
          register: result

        - name: Show result
          debug:
            msg: "{{ result }}"

