---
- hosts: localhost
  gather_facts: no
  
  pre_tasks:
    - name: Ensure environment variables are set
      block:
        - name: VAULT_TOKEN
          fail:
            msg: "VAULT_TOKEN environment variable is not set"
          when: lookup('env', 'VAULT_TOKEN') == ""

        - name: VAULT_ADDR
          fail:
            msg: "VAULT_ADDR environment variable is not set"
          when: lookup('env', 'VAULT_ADDR') == ""

        - name: Set Vars
          set_fact:
            vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
            vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"

  tasks:
    - name: List access policies from Vault
      community.hashi_vault.vault_list:
        url: "{{ vault_addr }}"
        path: "sys/policies/acl"
        validate_certs: false
      register: result
      
    - name: Debug Vault policies
      debug:
        msg: "{{ result['data']['data']['keys'] }}"

