---
- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "engine_name"
      prompt: "Please enter the engine name"
      private: no

  tasks:
    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_secrets"
        
