---
- hosts: localhost
  gather_facts: no
  vars:
    engine_type: kv
    engine_name: app-a
    secret_name: secrets-app-1

  pre_tasks:
    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "read_secrets"
        
    - when: not is_secret_empty
      debug:
        msg: "{{ secret_content }}"
