---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "create_policy"
        policy_name: "admin-policy"
