---
- name: Update Vault Secrets
  hosts: localhost
  gather_facts: no
  vars:
    engine_type: kv
    engine_name: app-a
    secret_name: secrets-app-1
    secret_kv:
      account_10: pass_11
  
  pre_tasks:
    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "read_secrets"

    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "update_secrets"

