---
- name: User prompts
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "engine_type"
      prompt: "Please enter the engine type (pki, ssh, or kv)"
      private: no
      default: "kv"

    - name: "engine_name"
      prompt: "Please enter the engine name"
      private: no

    - name: "secret_name"
      prompt: "Please enter the secret name"
      private: no

    - name: "secret_key"
      prompt: "Please enter the secret key"
      private: no

    - name: "secret_value"
      prompt: "Please enter the secret value"
      private: no
  
  pre_tasks:
    - name: Role Prechecks - Required Vars
      when: >
        engine_name is not defined or engine_name | trim == "" or
        engine_type is not defined or engine_type | trim == "" or
        secret_name is not defined or secret_name | trim == "" or
        secret_key is not defined or secret_key | trim == "" or
        secret_value is not defined or secret_value | trim == ""
      block:
        - name: Error message
          ansible.builtin.debug:
            msg: "Required variables are missing or empty"

        - name: Stop execution
          meta: end_play

    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_engines"

    - name: Validate engine exists
      when: engine_name not in existing_engines
      block:
        - name: Error message
          ansible.builtin.debug:
            msg: "Engine '{{ engine_name }}' does not exist."

        - name: Stop execution
          meta: end_play

    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "list_secrets"

    - name: Validate secret exists
      when: >
        secret_name not in existing_secrets or
        is_engine_empty
      block:
        - name: Error message
          ansible.builtin.debug:
            msg: "Secret '{{ secret_name }}' does not exist."

        - name: Stop execution
          meta: end_play

    - name: Vault role
      ansible.builtin.include_role:
        name: vault_role
      vars:
        user_action: "update_secret"


