---
allowed_domains:
  - "company.com"
  - "www.company.com"
allow_subdomains: true
max_ttl: "8760h"  # 1 year
key_usage:
  - "DigitalSignature"
  - "KeyEncipherment"
extended_key_usage:
  - "serverAuth"
allow_any_name: false
enforce_hostnames: true

