---
- name: Set current time 
  ansible.builtin.set_fact:
    current_time: "{{ lookup('pipe', 'date +%d_%m_%Y_%H_%M_%S') }}"

- name: Generate filename with current date and time
  ansible.builtin.set_fact:
    secret_filename: "{{ backup_dir }}/{{ secret_name }}_{{ current_time }}.yml"

- name: Create the file with secret content
  copy:
    content: "{{ secret_content | to_nice_yaml }}"
    dest: "{{ secret_filename }}"
  register: result

- name: Validate backup
  when: result['failed']
  block:
    - name: Error message
      ansible.builtin.debug:
        msg: "Temporary backup was not created"

    - name: Stop execution
      meta: end_play

- name: Show result
  ansible.builtin.debug: 
    msg: "Temporary backup created in this path: {{ result['dest'] }}"


