---
- name: Get Current time
  ansible.builtin.include_tasks:
    file: "time.yml"

- name: Role Prechecks - Required Vars
  when: >
        engine_name is not defined or 
        engine_type is not defined or
        secret_name is not defined or
        current_time is not defined
  block:
    - name: Error message
      ansible.builtin.debug:
        msg: |
          Required variables are missing:
          - engine_name
          - engine_type
          - secret_name
          - current_time

    - name: Stop execution
      meta: end_play

- name: Create backup
  when: engine_type in ["kv"]
  block:
    - name: Set var
      ansible.builtin.set_fact:
        secret_path: "{{ engine_name }}/data/{{ secret_name }}"

    - name: Get Secret
      uri:
        url: "{{ vault_addr }}/v1/{{ secret_path }}"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: [200, 201, 204, 404]
        return_content: true
        validate_certs: false
      register: result

    - name: Query was successful 
      when: result['status'] in [200, 201, 204]
      block:
        - name: Create Backup
          copy:
            content: "{{ result['json'] | to_json }}"
            dest: "{{ backup_dir + secret_name + current_time }}.json"

        - name: Show result
          ansible.builtin.debug:
            msg:
              - "The '{{ secret_name }}' secret was backed up successfully."
              - "Backup Path: {{ backup_dir + secret_name + current_time }}.json"

    - name: No backup required
      when: 
        - result['status'] == 404
        - user_action == "create_secret"
      block:
        - name: Set var 
          ansible.builtin.set_fact:
            is_engine_empty: true

        - name: User message
          ansible.builtin.debug:
            msg: 
              - "Engine is empty, no backup required"
              - "{{ result }}"
        - meta: end_play
    - name: Query failed
      when: 
        - result['status'] not in [200, 201, 204]
        - user_action != "create_secret"
      block:
        - name: Error message
          ansible.builtin.debug:
            msg: 
              - "Secret '{{ secret_name }}' was not created."
              - "{{ result }}"
              - "User action: {{ user_action }}"

        - name: Stop execution
          meta: end_play


