---
- name: Prechecks - Required vars
  when: >
    policy_name is undefined or
    policy_name == ""
  block:
    - name: Error message
      debug:
        msg: "The policy name '{{ policy_name }}' is either not defined or empty."

    - name: Stop execution
      meta: end_play

- name: Prechecks - Policy file
  block:
    - name: Set vars
      ansible.builtin.set_fact:
        policy_fullpath: "files/policies/{{ policy_name }}.hcl"
 
    - name: Set vars
      ansible.builtin.set_fact:
        policy_exists: "{{ policy_fullpath is file }}"

    - name: Error message
      when: not policy_exists
      block:
        - name: Error message  
          ansible.builtin.debug:
            msg: "Policy file {{ policy_fullpath }} does not exist."

        - name: Stop execution
          meta: end_play

- name: Prechecks - Policy format
  block:
    - name: Vault role
      ansible.builtin.command:
        cmd: "vault policy fmt {{ policy_fullpath }}"
      register: cmd_result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ cmd_result }}"

- name: Prechecks - Policy file
  when: 1 == 3
  block:
    - name: Vault role
      ansible.builtin.command:
        cmd: "vault policy write {{ policy_name }} {{ policy_fullpath }}"
      register: cmd_result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ cmd_result }}"
