---
- name: Role Prechecks - Required Vars
  when: >
        engine_name is not defined or engine_name | trim == "" or 
        engine_type is not defined or engine_type is not in valid_engine_types or 
        engine_type | trim == "" or
        secret_name is not defined or secret_name | trim == "" or
        backup_dir is not defined 
  block:
    - name: Error message
      ansible.builtin.debug:
        msg: |
          Required variables are missing or empty:
          - engine_name
          - engine_type
          - secret_name
          - backup_dir 

    - name: Stop execution
      meta: end_play

- name: Create Secret
  when: engine_type in ["kv"]
  block:
    - name: Set var
      ansible.builtin.set_fact:
        secret_path: "{{ engine_name }}/data/{{ secret_name }}"

    - name: Write Secret
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/{{ secret_path }}"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body: {
          'data': {'_': '_'}
          }
        status_code: [200, 201, 204, 404]
        body_format: json
        return_content: true
        validate_certs: false
      register: write_result

    - name: Show result
      when: write_result['status'] in [200, 201, 204]
      ansible.builtin.debug:
        msg: "Secret '{{ secret_name }}' was created successfully."

    - name: Write failed
      when: write_result['status'] == 404
      block:
        - name: Error message
          ansible.builtin.debug:
            msg: "Secret '{{ secret_name }}' was not created."

        - name: Stop execution
          meta: end_play

    - name: Unknown error
      when: write_result['status'] not in [200, 201, 204, 404]
      block:
        - name: Show result
          ansible.builtin.debug:
            msg: "ERROR: Unknown error has occurred"

        - name: Stop execution
          meta: end_play
