---
# --------------------------------------------------------------------------
# Purpose:
#   This file contains tasks to query vault secrets and their content.
#
# Required Parameters:
#   - engine_name
#   - engine_type
#
# Set Variables:
#   - is_secret_empty: A secret could exist with or without content.
#     type: bool
#   - secret_content: Content of a given secret.
#     type: dict
#
# Usage Notes:
# --------------------------------------------------------------------------

- name: Get Engines
  uri:
    url: "{{ vault_addr }}/v1/sys/internal/ui/mounts"
    method: GET
    headers:
      X-Vault-Token: "{{ vault_token }}"
    status_code: [200, 201, 204, 404]
    return_content: true
    validate_certs: false
  register: result

- name: Show result
  when: result['status'] == 404
  ansible.builtin.debug:
    msg: "Could not get engines."

- name: Existing engines
  when: result['status'] in [200, 201, 204]
  block:
    - name: Set var
      set_fact:
        existing_engines: "{{ result | 
          community.general.json_query('json.data.secret | keys(@)') | 
          map('regex_replace', '/', '') | list }}"

    - name: Show result
      debug:
        msg: "{{ existing_engines }}"
   



