---
- name: Set vars
  ansible.builtin.set_fact:
    existing_authmethods: []

- name: Get Authentication Methods
  ansible.builtin.uri:
    url: "{{ vault_addr }}/v1/sys/auth"
    method: GET
    headers:
      X-Vault-Token: "{{ vault_token }}"
    status_code: [200, 201, 204, 404]
    return_content: true
    validate_certs: false
  register: result

- name: Show result
  when: result['status'] == 404
  ansible.builtin.debug:
    msg: "Could not get authentication methods."

- name: Existing Authentication Methods
  when: result['status'] in [200, 201, 204]
  block:
    - name: Set var
      ansible.builtin.set_fact: 
        show_existing_authmethods: "{{ show_existing_authmethods | 
          default([]) + [{
            'name': item.key | regex_replace('/', ''), 
            'type': item.value.type 
          }] }}"
      loop: "{{ result['json']['data'] | dict2items }}"

    - name: Set var
      ansible.builtin.set_fact:
        existing_authmethods: "{{ existing_authmethods | 
          default([]) + [ item.key | regex_replace('/', '')] }}"
      loop: "{{ result['json']['data'] | dict2items }}"

    - name: Existing Authentication Methods
      ansible.builtin.debug:
        msg: "{{ show_existing_authmethods }}" 
   



