---
- name: Role Prechecks - Required Vars
  when: >
        engine_name is not defined or 
        engine_type is not defined or
        secret_name is not defined or
        backup_dir is not defined
  block:
    - name: Error message
      ansible.builtin.debug:
        msg: |
          Required variables are missing:
          - engine_name
          - engine_type
          - secret_name
          - backup_dir 

    - name: Stop execution
      meta: end_play

- name: Create temporary backup
  ansible.builtin.include_tasks:
    file: "backup_secret.yml"

- name: Create Secret
  when: engine_type in ["kv"]
  block:
    - name: Set var
      ansible.builtin.set_fact:
        secret_path: "{{ engine_name }}/data/{{ secret_name }}"

    - name: Get Secret
      uri:
        url: "{{ vault_addr }}/v1/{{ secret_path }}"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: [200, 201, 204, 404]
        return_content: true
        validate_certs: false
      register: result

    - name: Query failed
      when: result['status'] not in [200, 201, 204]
      block:

        - meta: end_play


    - name: Create body with existing and new data
      ansible.builtin.set_fact:
        data_combined: "{{ result['json']['data']['data'] | combine({secret_key: secret_value}) }}"

    - name: Set new body
      ansible.builtin.set_fact:
        body:
          data: "{{ data_combined }}"

    - name: Write Secret
      when: body is defined
      uri:
        url: "{{ vault_addr }}/v1/{{ secret_path }}"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body: "{{ body }}"
        status_code: [200, 201, 204, 404]
        body_format: json
        return_content: true
        validate_certs: false
      register: write_result

    - name: Show result
      when: write_result['status'] in [200, 201, 204]
      ansible.builtin.debug:
        msg: "Secret '{{ secret_name }}' was updated successfully."

    - name: Write failed
      when: write_result['status'] not in [200, 201, 204]
      block:
        - name: Show result
          ansible.builtin.debug:
            msg: "Secret '{{ secret_name }}' was not updated."

        - name: Stop execution
          meta: end_play
